services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    restart: always

  backend:
    build:
      context: ./backend
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - DATABASE_URL=postgres://postgres:postgres@db:5432/demand_forecasting
      - PYTHON_PATH=python3
      - JWT_SECRET=demand_forecasting_secret_key_123
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    depends_on:
      - ml_service
      - db
    restart: always

  ml_service:
    build:
      context: ./backend/ml_models
    ports:
      - "5001:5001"

  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=demand_forecasting
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
